import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.scss";
import CartContextProvider from "@/components/features/CartContext";

const roboto = Roboto({
  subsets: ["latin"],
  variable: "--font-roboto-sans", // опционально: CSS-variable для FVF
  weight: ["400", "700"], // если нужны конкретные веса
  display: "swap", // по желанию
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.className} ${roboto.variable}`}>
        <CartContextProvider>{children}</CartContextProvider>
      </body>
    </html>
  );
}
